name: Build latest Debian images

on:
  push:
    branches: [master]
    paths: ["debian/**"]

env:
  OS: debian
  DOCKER_REPO: ilyes512/php74-fpm

jobs:
  build_latest_debian:
    name: Build latest Debian
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: docker/build-push-action@v1
        with:
          repository: ${{ env.DOCKER_REPO }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
          dockerfile: ${{ env.OS }}/Dockerfile
          target: builder
          add_git_labels: true
          tag: ${{ env.OS }}-latest-builder
          tag_with_sha: true
      - uses: docker/build-push-action@v1
        with:
          repository: ${{ env.DOCKER_REPO }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
          dockerfile: ${{ env.OS }}/Dockerfile
          target: runtime
          add_git_labels: true
          tag: ${{ env.OS }}-latest-runtime
          tag_with_sha: true
